import { describe, it, expect, vi, beforeEach } from 'vitest'

vi.mock('fs', async (importOriginal) => {
  const actual = await importOriginal()
  return {
    ...actual,
    promises: {
      ...actual.promises,
      writeFile: vi.fn().mockResolvedValue(undefined),
      readFile: vi.fn().mockResolvedValue(
        '<svg xmlns="http://www.w3.org/2000/svg"><rect width="10" height="10"/></svg>'
      ),
      unlink: vi.fn().mockResolvedValue(undefined),
    },
  }
})

vi.mock('electron', () => ({ app: { getPath: vi.fn() } }))

const { convert, setShell, exportToFormat } = await import(
  '../../src/main/conversionService.js'
)

describe('ConversionService', () => {
  beforeEach(() => vi.clearAllMocks())

  describe('convert()', () => {
    it('delegates to shell.convert() and returns SVG from the output file', async () => {
      const mockShell = { convert: vi.fn().mockResolvedValue(undefined) }
      setShell(mockShell)

      const result = await convert(Buffer.from([0x01]))
      expect(result).toContain('<svg')
      expect(mockShell.convert).toHaveBeenCalledOnce()
      const [emfArg, svgArg] = mockShell.convert.mock.calls[0]
      expect(emfArg).toMatch(/schclip_.*\.emf$/)
      expect(svgArg).toMatch(/schclip_.*\.svg$/)
    })

    it('rejects when shell.convert() rejects with TIMEOUT', async () => {
      const mockShell = {
        convert: vi.fn().mockRejectedValue(new Error('TIMEOUT')),
      }
      setShell(mockShell)
      await expect(convert(Buffer.from([0x01]))).rejects.toThrow('TIMEOUT')
    })
  })

  describe('SVGO optimization (via convert())', () => {
    it('strips XML comments from SVG output', async () => {
      const svgWithComment =
        '<svg xmlns="http://www.w3.org/2000/svg" width="10mm" height="10mm" viewBox="0 0 10 10">' +
        '<!-- generated by inkscape -->' +
        '<rect width="10" height="10"/>' +
        '</svg>'

      const { promises: fsp } = await import('fs')
      fsp.readFile.mockResolvedValueOnce(svgWithComment)

      const mockShell = { convert: vi.fn().mockResolvedValue(undefined) }
      setShell(mockShell)

      const result = await convert(Buffer.from([0x01]))
      expect(result).not.toContain('<!-- generated by inkscape -->')
      expect(result).toContain('<svg')
      expect(result).toContain('viewBox="0 0 10 10"')
    })
  })
})

describe('exportToFormat()', () => {
  it('writes SVG content directly for format "svg" without calling shell', async () => {
    const mockShell = { execute: vi.fn().mockResolvedValue(undefined) }
    setShell(mockShell)
    const { promises: fsp } = await import('fs')

    const content = '<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>'
    await exportToFormat(content, 'svg', '/tmp/out.svg')

    expect(fsp.writeFile).toHaveBeenCalledWith('/tmp/out.svg', content, 'utf8')
    expect(mockShell.execute).not.toHaveBeenCalled()
  })

  it('calls _shell.execute() with correct PNG action string', async () => {
    const mockShell = { execute: vi.fn().mockResolvedValue(undefined) }
    setShell(mockShell)

    await exportToFormat('<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>', 'png', '/tmp/out.png')

    expect(mockShell.execute).toHaveBeenCalledOnce()
    const [actionsArg] = mockShell.execute.mock.calls[0]
    expect(actionsArg).toContain('export-type:png')
    expect(actionsArg).toContain('export-dpi:300')
    expect(actionsArg).toContain('export-filename:/tmp/out.png')
  })

  it('uses "jpeg" (not "jpg") and adds quality for JPG format', async () => {
    const mockShell = { execute: vi.fn().mockResolvedValue(undefined) }
    setShell(mockShell)

    await exportToFormat('<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>', 'jpg', '/tmp/out.jpg')

    const [actionsArg] = mockShell.execute.mock.calls[0]
    expect(actionsArg).toContain('export-type:jpeg')
    expect(actionsArg).toContain('export-jpeg-quality:95')
    expect(actionsArg).toContain('export-dpi:300')
  })

  it('omits DPI for PDF format', async () => {
    const mockShell = { execute: vi.fn().mockResolvedValue(undefined) }
    setShell(mockShell)

    await exportToFormat('<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>', 'pdf', '/tmp/out.pdf')

    const [actionsArg] = mockShell.execute.mock.calls[0]
    expect(actionsArg).toContain('export-type:pdf')
    expect(actionsArg).not.toContain('export-dpi')
  })

  it('throws SHELL_NOT_INITIALIZED when shell is not set and format is png', async () => {
    setShell(null)
    await expect(
      exportToFormat('<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>', 'png', '/tmp/out.png')
    ).rejects.toThrow('SHELL_NOT_INITIALIZED')
  })
})
