import { describe, it, expect, vi, beforeEach } from 'vitest'

vi.mock('fs', async (importOriginal) => {
  const actual = await importOriginal()
  return {
    ...actual,
    promises: {
      ...actual.promises,
      writeFile: vi.fn().mockResolvedValue(undefined),
      readFile: vi.fn().mockResolvedValue(
        '<svg xmlns="http://www.w3.org/2000/svg"><rect width="10" height="10"/></svg>'
      ),
      unlink: vi.fn().mockResolvedValue(undefined),
    },
  }
})

vi.mock('electron', () => ({ app: { getPath: vi.fn() } }))

// ── Mocks for dynamic imports inside exportToFormat() ─────────────────────

const {
  mockResvgCtor,
  mockAsPng,
  mockSharp,
  mockFlattenFn,
  mockJpegFn,
  mockToBuffer,
  mockPDFDocCtor,
  mockPDFDocInstance,
  mockSVGtoPDF,
} = vi.hoisted(() => {
  const mockAsPng = vi.fn().mockReturnValue(Buffer.from('png-data'))
  const mockRender = vi.fn().mockReturnValue({ asPng: mockAsPng })
  const mockResvgCtor = vi.fn(function () { this.render = mockRender })

  const mockToBuffer = vi.fn().mockResolvedValue(Buffer.from('jpg-data'))
  const mockJpegFn = vi.fn().mockReturnValue({ toBuffer: mockToBuffer })
  const mockFlattenFn = vi.fn().mockReturnValue({ jpeg: mockJpegFn })
  const mockSharp = vi.fn().mockReturnValue({ flatten: mockFlattenFn })

  const mockSVGtoPDF = vi.fn()

  // pdf doc that auto-fires data + end when doc.end() is called
  const listeners = {}
  const mockPDFDocInstance = {
    on: vi.fn().mockImplementation((event, cb) => { listeners[event] = cb }),
    addPage: vi.fn(),
    end: vi.fn().mockImplementation(() => {
      if (listeners.data) listeners.data(Buffer.from('pdf-chunk'))
      if (listeners.end) listeners.end()
    }),
  }
  const mockPDFDocCtor = vi.fn(function () {
    this.on = mockPDFDocInstance.on
    this.addPage = mockPDFDocInstance.addPage
    this.end = mockPDFDocInstance.end
  })

  return {
    mockResvgCtor,
    mockAsPng,
    mockSharp,
    mockFlattenFn,
    mockJpegFn,
    mockToBuffer,
    mockPDFDocCtor,
    mockPDFDocInstance,
    mockSVGtoPDF,
  }
})

vi.mock('@resvg/resvg-js', () => ({ Resvg: mockResvgCtor }))
vi.mock('sharp', () => ({ default: mockSharp }))
vi.mock('pdfkit', () => ({ default: mockPDFDocCtor }))
vi.mock('svg-to-pdfkit', () => ({ default: mockSVGtoPDF }))

const { convert, setShell, exportToFormat } = await import(
  '../../src/main/conversionService.js'
)

describe('ConversionService', () => {
  beforeEach(() => vi.clearAllMocks())

  describe('convert()', () => {
    it('delegates to shell.convert() and returns SVG from the output file', async () => {
      const mockShell = { convert: vi.fn().mockResolvedValue(undefined) }
      setShell(mockShell)

      const result = await convert(Buffer.from([0x01]))
      expect(result).toContain('<svg')
      expect(mockShell.convert).toHaveBeenCalledOnce()
      const [emfArg, svgArg] = mockShell.convert.mock.calls[0]
      expect(emfArg).toMatch(/schclip_.*\.emf$/)
      expect(svgArg).toMatch(/schclip_.*\.svg$/)
    })

    it('rejects when shell.convert() rejects with TIMEOUT', async () => {
      const mockShell = {
        convert: vi.fn().mockRejectedValue(new Error('TIMEOUT')),
      }
      setShell(mockShell)
      await expect(convert(Buffer.from([0x01]))).rejects.toThrow('TIMEOUT')
    })
  })

  describe('SVGO optimization (via convert())', () => {
    it('strips XML comments from SVG output', async () => {
      const svgWithComment =
        '<svg xmlns="http://www.w3.org/2000/svg" width="10mm" height="10mm" viewBox="0 0 10 10">' +
        '<!-- generated by converter -->' +
        '<rect width="10" height="10"/>' +
        '</svg>'

      const { promises: fsp } = await import('fs')
      fsp.readFile.mockResolvedValueOnce(svgWithComment)

      const mockShell = { convert: vi.fn().mockResolvedValue(undefined) }
      setShell(mockShell)

      const result = await convert(Buffer.from([0x01]))
      expect(result).not.toContain('<!-- generated by converter -->')
      expect(result).toContain('<svg')
      expect(result).toContain('viewBox="0 0 10 10"')
    })
  })
})

describe('exportToFormat()', () => {
  const SVG = '<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>'

  beforeEach(() => vi.clearAllMocks())

  it('writes SVG content directly for format "svg"', async () => {
    const { promises: fsp } = await import('fs')
    await exportToFormat(SVG, 'svg', '/tmp/out.svg')
    expect(fsp.writeFile).toHaveBeenCalledWith('/tmp/out.svg', SVG, 'utf8')
  })

  it('renders PNG via Resvg at 300/96 zoom and writes the buffer', async () => {
    const { promises: fsp } = await import('fs')
    await exportToFormat(SVG, 'png', '/tmp/out.png')

    expect(mockResvgCtor).toHaveBeenCalledWith(SVG, { fitTo: { mode: 'zoom', value: 300 / 96 } })
    expect(mockAsPng).toHaveBeenCalledOnce()
    expect(fsp.writeFile).toHaveBeenCalledWith('/tmp/out.png', Buffer.from('png-data'))
  })

  it('renders JPEG via Resvg→sharp at quality 95 and writes the buffer', async () => {
    const { promises: fsp } = await import('fs')
    await exportToFormat(SVG, 'jpg', '/tmp/out.jpg')

    expect(mockResvgCtor).toHaveBeenCalledWith(SVG, { fitTo: { mode: 'zoom', value: 300 / 96 } })
    expect(mockSharp).toHaveBeenCalledWith(Buffer.from('png-data'))
    expect(mockFlattenFn).toHaveBeenCalledWith({ background: '#ffffff' })
    expect(mockJpegFn).toHaveBeenCalledWith({ quality: 95 })
    expect(mockToBuffer).toHaveBeenCalledOnce()
    expect(fsp.writeFile).toHaveBeenCalledWith('/tmp/out.jpg', Buffer.from('jpg-data'))
  })

  it('generates vector PDF via pdfkit+svg-to-pdfkit and writes the buffer', async () => {
    const { promises: fsp } = await import('fs')
    await exportToFormat(SVG, 'pdf', '/tmp/out.pdf')

    expect(mockPDFDocCtor).toHaveBeenCalledWith({ autoFirstPage: false })
    const docInstance = mockPDFDocCtor.mock.instances[0]
    expect(mockPDFDocInstance.addPage).toHaveBeenCalledWith({ size: [595.28, 841.89], margin: 0 })
    expect(mockSVGtoPDF).toHaveBeenCalledWith(docInstance, SVG, 0, 0, { width: 595.28, height: 841.89 })
    expect(fsp.writeFile).toHaveBeenCalledWith(
      '/tmp/out.pdf',
      Buffer.concat([Buffer.from('pdf-chunk')])
    )
  })

  it('sizes the PDF page to match SVG dimensions in points', async () => {
    const svgWithDims =
      '<svg xmlns="http://www.w3.org/2000/svg" width="200mm" height="150mm"><rect/></svg>'
    const expectedW = 200 * (72 / 25.4)
    const expectedH = 150 * (72 / 25.4)

    await exportToFormat(svgWithDims, 'pdf', '/tmp/out.pdf')

    expect(mockPDFDocInstance.addPage).toHaveBeenCalledWith({
      size: [expectedW, expectedH],
      margin: 0,
    })
    expect(mockSVGtoPDF).toHaveBeenCalledWith(
      mockPDFDocCtor.mock.instances[0],
      svgWithDims,
      0,
      0,
      { width: expectedW, height: expectedH }
    )
  })

  it('throws "Formato não suportado" for unknown format', async () => {
    await expect(exportToFormat(SVG, 'xyz', '/tmp/out.xyz')).rejects.toThrow(
      'Formato não suportado: xyz'
    )
  })
})
