import { describe, it, expect, vi, beforeEach } from 'vitest'

vi.mock('fs', async (importOriginal) => {
  const actual = await importOriginal()
  return {
    ...actual,
    promises: {
      ...actual.promises,
      writeFile: vi.fn().mockResolvedValue(undefined),
      readFile: vi.fn().mockResolvedValue(
        '<svg xmlns="http://www.w3.org/2000/svg"><rect width="10" height="10"/></svg>'
      ),
      unlink: vi.fn().mockResolvedValue(undefined),
    },
  }
})

vi.mock('electron', () => ({ app: { getPath: vi.fn() } }))

const { convert, setShell, isValidSVG, getSVGMetadata, exportToFormat } = await import(
  '../../src/main/conversionService.js'
)

describe('ConversionService', () => {
  beforeEach(() => vi.clearAllMocks())

  // ── isValidSVG() ─────────────────────────────────────────────────────────

  describe('isValidSVG()', () => {
    it('returns true for valid SVG with content', () => {
      expect(
        isValidSVG('<svg xmlns="..."><rect x="0" y="0" width="10" height="10"/></svg>')
      ).toBe(true)
    })

    it('returns false for empty string', () => {
      expect(isValidSVG('')).toBe(false)
    })

    it('returns false for SVG with empty body', () => {
      expect(isValidSVG('<svg xmlns="..."></svg>')).toBe(false)
    })

    it('returns false for non-SVG content', () => {
      expect(isValidSVG('Hello world')).toBe(false)
    })
  })

  // ── getSVGMetadata() ──────────────────────────────────────────────────────

  describe('getSVGMetadata()', () => {
    it('extracts width and height from svg root element', () => {
      const svg =
        '<svg xmlns="http://www.w3.org/2000/svg" width="210mm" height="148mm"><rect width="50" height="50"/></svg>'
      const meta = getSVGMetadata(svg, 500)
      expect(meta.width).toBe('210mm')
      expect(meta.height).toBe('148mm')
    })

    it('returns unknown when svg has no width/height attributes', () => {
      const svg =
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect/></svg>'
      const meta = getSVGMetadata(svg, 100)
      expect(meta.width).toBe('unknown')
      expect(meta.height).toBe('unknown')
    })

    it('reports sizeBytes as byte length of the SVG string', () => {
      const svg = '<svg></svg>'
      const meta = getSVGMetadata(svg, 0)
      expect(meta.sizeBytes).toBe(Buffer.byteLength(svg, 'utf8'))
    })

    it('passes through conversionMs unchanged', () => {
      const meta = getSVGMetadata('<svg width="1" height="1"></svg>', 1234)
      expect(meta.conversionMs).toBe(1234)
    })
  })

  // ── convert() ────────────────────────────────────────────────────────────

  describe('convert()', () => {
    it('delegates to shell.convert() and returns SVG from the output file', async () => {
      const mockShell = { convert: vi.fn().mockResolvedValue(undefined) }
      setShell(mockShell)

      const result = await convert(Buffer.from([0x01]))
      expect(result).toContain('<svg')
      expect(mockShell.convert).toHaveBeenCalledOnce()
      // shell.convert receives (emfPath, svgPath, timeout) — both are tmp paths
      const [emfArg, svgArg] = mockShell.convert.mock.calls[0]
      expect(emfArg).toMatch(/schclip_.*\.emf$/)
      expect(svgArg).toMatch(/schclip_.*\.svg$/)
    })

    it('rejects when shell.convert() rejects with TIMEOUT', async () => {
      const mockShell = {
        convert: vi.fn().mockRejectedValue(new Error('TIMEOUT')),
      }
      setShell(mockShell)
      await expect(convert(Buffer.from([0x01]))).rejects.toThrow('TIMEOUT')
    })
  })

  // ── SVGO optimization (via convert()) ────────────────────────────────────

  describe('SVGO optimization (via convert())', () => {
    it('strips XML comments from SVG output', async () => {
      const svgWithComment =
        '<svg xmlns="http://www.w3.org/2000/svg" width="10mm" height="10mm" viewBox="0 0 10 10">' +
        '<!-- generated by inkscape -->' +
        '<rect width="10" height="10"/>' +
        '</svg>'

      const { promises: fsp } = await import('fs')
      fsp.readFile.mockResolvedValueOnce(svgWithComment)

      const mockShell = { convert: vi.fn().mockResolvedValue(undefined) }
      setShell(mockShell)

      const result = await convert(Buffer.from([0x01]))
      expect(result).not.toContain('<!-- generated by inkscape -->')
      expect(result).toContain('<svg')
      expect(result).toContain('viewBox="0 0 10 10"')
    })
  })
})

describe('exportToFormat()', () => {
  it('writes SVG content directly for format "svg" without calling shell', async () => {
    const mockShell = { execute: vi.fn().mockResolvedValue(undefined) }
    setShell(mockShell)
    const { promises: fsp } = await import('fs')

    const content = '<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>'
    await exportToFormat(content, 'svg', '/tmp/out.svg')

    expect(fsp.writeFile).toHaveBeenCalledWith('/tmp/out.svg', content, 'utf8')
    expect(mockShell.execute).not.toHaveBeenCalled()
  })

  it('calls _shell.execute() with correct PNG action string', async () => {
    const mockShell = { execute: vi.fn().mockResolvedValue(undefined) }
    setShell(mockShell)

    await exportToFormat('<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>', 'png', '/tmp/out.png')

    expect(mockShell.execute).toHaveBeenCalledOnce()
    const [actionsArg] = mockShell.execute.mock.calls[0]
    expect(actionsArg).toContain('export-type:png')
    expect(actionsArg).toContain('export-dpi:300')
    expect(actionsArg).toContain('export-filename:/tmp/out.png')
  })

  it('uses "jpeg" (not "jpg") and adds quality for JPG format', async () => {
    const mockShell = { execute: vi.fn().mockResolvedValue(undefined) }
    setShell(mockShell)

    await exportToFormat('<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>', 'jpg', '/tmp/out.jpg')

    const [actionsArg] = mockShell.execute.mock.calls[0]
    expect(actionsArg).toContain('export-type:jpeg')
    expect(actionsArg).toContain('export-jpeg-quality:95')
    expect(actionsArg).toContain('export-dpi:300')
  })

  it('omits DPI for PDF format', async () => {
    const mockShell = { execute: vi.fn().mockResolvedValue(undefined) }
    setShell(mockShell)

    await exportToFormat('<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>', 'pdf', '/tmp/out.pdf')

    const [actionsArg] = mockShell.execute.mock.calls[0]
    expect(actionsArg).toContain('export-type:pdf')
    expect(actionsArg).not.toContain('export-dpi')
  })
})
